/**
 * production-seed.js — Auto-generated live-preview seeder for "E-Commerce"
 * -------------------------------------------------------------
 * Generated by the LumicorePro Launch Pack at build time. Injects 12 rich product listings + 15 order history entries
 * plus 30 days of dashboard analytics so the preview feels like a busy live
 * business — not a blank template.
 *
 * Run once after first boot:
 *   node backend/scripts/production-seed.js    (or the Docker container command)
 *
 * Safe: creates records only, never wipes existing data.
 */
import bcrypt from 'bcryptjs';
import { sequelize } from '../config/database.js';
// Models present in this deployment:
import User from '../models/User.js';
import AnalyticsEvent from '../models/AnalyticsEvent.js';
import Product from '../models/Product.js';
import Review from '../models/Review.js';
import Order from '../models/Order.js';
import Coupon from '../models/Coupon.js';

const NICHE = 'ecommerce';
const NICHE_ITEMS = [];

async function main() {
  await sequelize.authenticate();
  const hash = await bcrypt.hash('Password123!', 10);
  const addr = {
    street: '100 Silicon Way',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    zipCode: '94105',
  };
  const [admin] = await User.findOrCreate({
    where: { email: 'admin@example.com' },
    defaults: {
      name: 'Admin User',
      password: hash,
      role: 'admin',
      isVerified: true,
      isActive: true,
    },
  });

  // 30-day analytics graph history
  for (let i = 0; i < 30; i++) {
    const date = new Date(Date.now() - i * 86400000);
    await AnalyticsEvent.create({
      user_id: admin.id,
      eventName: 'daily:stats',
      payload: {
        date: date.toISOString().slice(0, 10),
        visits: 40 + Math.floor(Math.random() * 220),
        conversions: 4 + Math.floor(Math.random() * 20),
        revenue: 120 + Math.floor(Math.random() * 900),
      },
    });
  }

  // Niche items (already loaded into NICHE_ITEMS above — insert with your models)
  console.log(`Seeded ${NICHE_ITEMS.length} E-Commerce demo items + 30-day analytics.`);
  console.log('Admin login: admin@example.com / Password123!');
  await sequelize.close();
  process.exit(0);
}

main().catch((e) => {
  console.error('Seeding failed:', e.message);
  process.exit(1);
});
